- name: Ensure dot files are deployed.
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '../../Bash/.bashrc', dest: '~' }
    - { src: '../../Bash/.bash_aliases', dest: '~' }
    - { src: '../../.gitconfig', dest: '~' }